### ISSUE TITLE
Inexactness in subsubsection 2.1.1 "Subspaces and bases"

### ISSUE THREAD

**Issue by Danielwohl** [gamma-opt/optimisation-notes#8]
The third remark should be probably:
If a proper subspace has dimension m < n, then it means that there are (n − m) **orthogonal** (perpendicular) directions
in $R^n$ that are perpendicular to the subspace. That is, there are nonzero vectors $a_i$ that are orthogonal to each other and to S.

Sorry if mistaken

**Comment by FabsOliveira** [comment]
Good point. I am thinking of removing the perpendicular in brackets since it is a bit redundant. How about:

_If a proper subspace has dimension m < n, then it means that there are (n − m)  directions in $R^n$ that are perpendicular to the subspace and to each other. That is, there are nonzero vectors $a_i$ that are orthogonal to each other and to S._

I think in this case it is just as precise but a bit less redundant.

**Comment by FabsOliveira** [comment]
Adressed in
